### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by BeyoncesHomeboy** [getferdi/ferdi#1097]
I'm running Mac OS Big Sur on a macbook pro 16" and Ferdi is always using 20-24% cpu. Every time I run it the laptop kicks up the fan speed which in macbook is rare (as they love to cook the internals) and if I start doing anything somewhat heavy or multitasking the system starts lagging hard!

**Comment by jsbase** [comment]
same here.. i have to uninstalled unit it is fixed

**Comment by Just-Insane** [comment]
This is was seen previously with darkmode... looks like it's still a problem, when I enable darkmode my Ferdi CPU usage goes from 12.7% to over 300%.

**Comment by BeyoncesHomeboy** [comment]
> This is was seen previously with darkmode... looks like it's still a problem, when I enable darkmode my Ferdi CPU usage goes from 12.7% to over 300%.

how many things do you have open that it's using 12.7% of cpu? Asking so I can make a reference to my performance.

**Comment by bbbart** [comment]
Same here on Macbook Air/Linux. Fans are nearly constantly running full speed whenever Ferdi is open (same issue with Franz in the past).

I simply run Ferdi with [`cpulimit`](https://github.com/opsengine/cpulimit) now to keep it somewhat under control.

I actually don't think Ferdi is to blame here. I believe it has to do with either `electron` or the web services themselves. I'm running eight services on Ferdi (Mattermost, Telegram, Messenger, Whatsapp and 4 x Slack). What about you?

**Comment by Finnitio** [comment]
I have very high CPU usage from Ferdi when in dark mode. It is the GPU Task in Ferdi. Windows 10, i7-5600U.

**Comment by oreillygshane** [comment]
Also having the same issue

**Comment by catap** [comment]
Let me share an example how much Ferdi consume CPU:

<img width="1077" alt="Screenshot 2021-02-07 at 17 57 13" src="https://user-images.githubusercontent.com/37775/107153472-09ffa500-696e-11eb-9f5c-67f298979dcb.png">

**Comment by oreillygshane** [comment]
Still an issue on Version 5.6.0-beta.5 (5.6.0-beta.5.2741) with/without Dark Mode enabled:

This has made Ferdi unusable

**Comment by diegobersanetti** [comment]
Still an issue on 5.6.0 with Dark mode on Ubuntu 20.04
![Screenshot from 2021-08-25 09-32-15](https://user-images.githubusercontent.com/317627/130747542-8802a169-9236-46f2-9060-dac22b2488c4.png)

**Comment by vraravam** [comment]
@diegobersanetti - can you please also post the numbers without the darkmode?

**Comment by TalZiv** [comment]
Hi, 
I was encountering  the same issue and it seems that disabling dark mode in Ferdi and restarting Ferdi does reduce the cpu. I am using Mac BigSur 11.6  and Ferdi 5.6.2

**Comment by vraravam** [comment]
Thanks for getting back @TalZiv . Yes, the darkmode plugin is not in our control. Since it tries to render contrasting colors based on the user's OS choice, the service-recipe's default colors and then the overrides from the darkmode library, it can be very cumbersome for the overall process. Unfortunately, this is not something we can do a lot about.

**Comment by polson** [comment]
Ferdi uses 115% of cpu when idle for me, with 8 services
![CleanShot 2021-09-29 at 12 16 22](https://user-images.githubusercontent.com/302882/135317458-b6f0a8d3-5ab4-43b7-803f-ed94b7e72535.png)

**Comment by vraravam** [comment]
@polson - which version of Ferdi are you on? Could you please try the latest nightly? We have upgraded electron to the latest version, and other dependencies have been upgraded as well.

**Comment by TheSasch** [comment]
I also have this issue with 5.6.2 also on MBP i9 8 Core. Installed with homebrew
