### ISSUE TITLE
Ferdi Tray icon issue

### ISSUE THREAD

**Issue by prvn-pa** [getferdi/ferdi#1189]
**Bug description:**
In Gnome 3.38, the ferdi tray icon doubles (attached SS) whenever there is a screen lock or reloading (Alt+F2). The issue is persistent with Appimage as well as AUR and Flatpak.

**Steps to reproduce:**
1. Install Ferdi
2. Enable Tray Icon
3. Lock the screen or reload the desktop
4. Now, two tray icons should be visible

**Expected behavior**
There should be one icon per application. This bug seems to create a dummy icon on tray.

**Screenshots**
![Screenshot from 2021-02-05 11-01-50](https://user-images.githubusercontent.com/55174721/106994419-bc830c80-67a2-11eb-8f80-0e28755fa7a2.png)

**Environment:**

- Operating System: Manjaro Linux 
- Ferdi Version: 5.5
- Server: Exists in Ferdi, Franz and Using without an account

**Comment by pdimens** [comment]
Can confirm this on Gnome 3.8 via Manjaro Arch Linux with `ferdi-git` installed via AUR:
![image](https://user-images.githubusercontent.com/19176506/107242221-5dff9d80-69f1-11eb-9c4b-7603baaf435a.png)

**Comment by pulver22** [comment]
Same issues on Ubuntu 18.04 with Gnome 3.28.4

**Comment by prvn-pa** [comment]
The issue is no longer persists in 5.5.10 version from official repositories of Manjaro Linux. Not sure about the changes, but no longer the second icon is created.

**Comment by pulver22** [comment]
I am on 5.6.0-n15 and the error is still there.

**Comment by DenysMb** [comment]
Please, reopen this issue.
I can confirm that the version from official Manjaro repositories (ferdi-5.5.0-10) fixed this bug but this version is only available for Manjaro users (although you can download the .zst file from their repositories and install it in Arch Linux, like I did - [link here from Brazil's mirror](https://manjaro.c3sl.ufpr.br/unstable/community/x86_64/ferdi-5.5.0-10-x86_64.pkg.tar.zst)).
It's better to keep this issue open until it's fixed for all platform, through developers release.

**Comment by prvn-pa** [comment]
Based on @DenysMb comment, reopening the issue.

**Comment by pulver22** [comment]
I got the same error with the new nightly 5.6.0-n48

**Comment by vraravam** [comment]
Can all of you please try the new `beta.6`?

**Comment by kris7t** [comment]
@vraravam It's still broken in the current beta (and also on `develop`). I'll get around to this, eventually, but it will likely require writing our own [StatusNotifierItem](https://freedesktop.org/wiki/Specifications/StatusNotifierItem/) implementation (Chromium's built-in one just doesn't handle enough edge cases atm).

**Comment by vraravam** [comment]
In that case, lets keep this for after 5.6?  we need to have minimal changes and get to releasing 5.6 @kris7t

**Comment by pulver22** [comment]
Still present in 5.6.1-nightly43

**Comment by vraravam** [comment]
Is this fixed with this morning's latest nightly?

**Comment by pulver22** [comment]
![image](https://user-images.githubusercontent.com/6864853/142031617-a97ea1e6-b5ca-4032-8595-a373b478a110.png)
 I tried the today's nightly (#7) but I still have the same error. After blocking the system and login in again, a second icon (invisible) is created.
 
 I'm on Ubuntu 18.04.

**Comment by mhatvan** [comment]
I might have some time available in the next few days to take a look at this.

**Comment by keirak420** [comment]
The above fix seems not to have been accepted due to the forced tray icon changes.

 How can we fix the duplicate tray icons without force enabling the tray icon?
