### ISSUE TITLE
Module @meetfranz/theme/lib/index.js cannot be found on launch

### ISSUE THREAD

**Issue by nullket** [getferdi/ferdi#1426]
**Bug description:**

Ferdi doest not open the GUI. I am using Ubuntu 20.04. Using a .desktop shortcut in Linux I get no feedback at all. With a process monitor I can see that the process keeps running but no GUI opens. On further investigating I started Ferdi via shell and got the traceback attached in the debug section of this issue

**Steps to reproduce:**

I was only able to test it on Ubuntu 20.04.
1. Build the current code (in my case with docker) or use the gfolder nightly [Ferdi-amd64-1261c4aa](https://drive.google.com/drive/folders/1vAk84hvZ5ftN6nWv4vv2a088efqtk7av)
2. Install
3. Try to launch
4. When launched via shell, you should see the error

**Expected behavior**

Ferdi starts correctly

**Environment:**

- Operating System: Ubuntu 20.04
- Ferdi Version: 5.6.0-nightly.18
- Server: Using without an account 

- Debug information:
Crash after running `/opt/Ferdi/ferdi`
```bash
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/opt/Ferdi/resources/app.asar/node_modules/@meetfranz/theme/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:310:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:523:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:874:27)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/Ferdi/resources/app.asar/config.js:1:1307)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

**Comment by vraravam** [comment]
I am not sure if the `Ferdi-amd64-*` (ie without the extension) is a full-fledged/self-contained archive. (SInce I am not a linux user, I didn't know what other files to grab from my docker container).

Could you please try with the `.deb` since you are anyway using ubuntu? I assume `.deb` packages are self-contained. If the problem still persists, we will have toe diagnose whether there's truly an issue in the packaging.

**Comment by nullket** [comment]
That was not very clear in my bug description. This error occurs when using the .debs. I have never tried something else. Happens for example with: https://drive.google.com/file/d/1nBDPG9QVZJIOSvjl8qYoIdqbbvwrdSph/view?usp=sharing

**Comment by nullket** [comment]
So I double checked to be sure, that it is not system configurations fault: I just built it using docker (thanks again) and then uploaded the deb (based on https://github.com/getferdi/ferdi/commit/9e63320086488899303a0efc63f678fe38343e2c which is the newest commit by the time writing this) to a brand new 20.04 VM. The VM won't launch ferdi either (same error as above).

**Comment by vraravam** [comment]
@nullket - pls try now. (Sorry, the PR closed the bug ticket as well accidentally)

**Comment by nullket** [comment]
With https://github.com/getferdi/ferdi/commit/aa68e324e945275ea7185821cda79ea7fa6afc9d (resulting in `Ferdi-amd64-aa68e324.deb`) the problem exactly remains the same.

**Comment by vraravam** [comment]
Maybe @kris7t can chime in - since he builds and runs on linux?

**Comment by vraravam** [comment]
btw - we were able to release the [latest nightly](https://github.com/getferdi/nightlies/releases/tag/v5.6.0-nightly.48) from earlier today. Please try that out - while we fix the Docker issues in a couple of days?

**Comment by kris7t** [comment]
I'm not on a distro that uses deb packages, but I'll try and spin up a virtual machine to check when I'll have time.

**Comment by nullket** [comment]
Let me know if I can provide you some more useful debug output (like [this tree output](https://pastebin.com/vzp7YJ9Y) or the files of `/opt/ferdi`) to save you some time. 

Exciting! Nightly releases are working again. I just installed the latest and it seems to work fine :)

**Comment by vraravam** [comment]
@nullket - since the "reference CI builds" for nightly are out, imo, it might be a good idea to to a pkgdiff of the deb artifact from the nightly process vs the one that is created via Docker - that might point us to the right direction. Could you please do that and report back?

**Comment by nullket** [comment]
I simply compared [nightly.48](https://github.com/getferdi/nightlies/releases/tag/v5.6.0-nightly.48) with my build from earlier based on https://github.com/getferdi/ferdi/commit/9e63320086488899303a0efc63f678fe38343e2c 

How do i get the sha for a nightly? No way right? I would need to use the nightly branch and its travis commit. As the last nightly is based on https://github.com/getferdi/ferdi/commit/9e63320086488899303a0efc63f678fe38343e2c we might can differences in the package info as listed below ;) 

**The package info**
differences are just 
- version 48 vs 40 what makes sense as I used 9e63320 and not the travis commit (to avoid rebuilding)
- installation size 334202 vs 321641 (see files missing below)

**File differences** (removed entries which have the status unchanged)

Name | Status | Delta | VisualDiff
-- | -- | -- | --
/opt/Ferdi/resources/app.asar.unpacked/recipes/all.json | removed
/opt/Ferdi/resources/app.asar.unpacked/recipes/NewsBlur.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/TickTick.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/airtable.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/amazon-work-mail.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/android-messages.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/anonaddy.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/anydo.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/asana.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/azure-devops.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/bigbluebutton.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/bip.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/bitbucket.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/campuswire.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/canvas.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/chatwork.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/ciscospark.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/clickup.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/cliq.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/clockify.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/clubhouse.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/devdocs.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/discord.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/disqus.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/element.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/enterprise-owa.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/epicgames.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/erepublik.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/evernote.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/ex-google-voice.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/facebook.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/facebookpages.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/fastmail.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/feedly.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/figma.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/fleep.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/flowdock.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/franz-custom-website.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/gadugadu.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/github.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/github_entreprise.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/gitlab.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/gitter.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/glowingbear.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/gmail.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/google-contacts.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/googlecalendar.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/googleclassroom.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/googledrive.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/googlekeep.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/googlemeet.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/googlepodcasts.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/gotomeeting.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/grape.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/groupme.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/guilded.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/habitica.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/hackmd.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/hangouts.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/hangoutschat.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/harvest.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/hipchat.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/icloud-reminders.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/icq.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/idobata.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/infomaniak-mail.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/instagram.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/intercom.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/irccloud.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/jira.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/jitsi.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/kaizala.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/kimaicloud.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/lark.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/lastpass.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/linkedin.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/mailbox.org.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/mastodon.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/mattermost.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/messenger.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/monday.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/monicahq.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/msteams.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/mstodo.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/mysms.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/netatmo-energy.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/nextcloud-calendar.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/nextcloud-carnet.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/nextcloud-cospend.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/nextcloud-talk.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/nextcloud-tasks.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/nextcloud.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/nextdoor.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/noisli.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/notion.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/office365-owa.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/onenote.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/outlook.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/pinterest.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/plurk.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/pocket.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/pomodoro-tracker.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/proton-mail.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/pulsesms.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/pushbullet.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/rainloop.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/reddit.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/redditchat.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/riseup.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/rocketchat.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/roundcube.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/sendtask.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/simplenote.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/skype.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/slack.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/slite.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/snapdrop.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/stackexchange.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/standardnotes.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/steamchat.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/stride.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/sync.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/tawk.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/teamwork-projects.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/telegram-react.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/telegram.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/thelounge.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/threema.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/todoist.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/toggl.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/trello.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/tutanota.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/tweetdeck.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/twist.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/twitch.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/twitter-dm.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/twitter.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/unraid.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/vk.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/voxer.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/webex-teams.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/wechat.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/whatsapp.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/wire.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/withspectrum.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/workplace.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/wrike.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/xing.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/yahoo-mail.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/yammer.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/youtrack.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/youtubemusic.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/zalo.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/zendesk.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/zenhub.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/zeplin.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/zimbra.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/zoho.tar.gz | removed | &nbsp; | &nbsp;
/opt/Ferdi/resources/app.asar.unpacked/recipes/zulip.tar.gz | removed | &nbsp;

**Comment by vraravam** [comment]
That's pointing to the packaged `recipes` missing from the build. But, that doesn't throw any light on the missing reference file: `@meetfranz/theme`.

**Comment by vraravam** [comment]
>  How do i get the sha for a nightly?

fyi - this can be obtained from the `buildInfo.json` file that is packaged into the application. I'm not sure of the exact folder location within the artifact - but, the filename is the one above.

**Comment by kris7t** [comment]
After #1453, the file list seems identical between the nightly package and the one built inside Docker. @nullket, can you check whether the package build inside Docker works for you now?

**Comment by nullket** [comment]
Based on https://github.com/getferdi/ferdi/commit/1886c8abed32e33f0f547c069c674b79279cf931 is does still not work. Now it is `ui` with `@meetfranz/ui/lib/index.js` missing
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/opt/Ferdi/resources/app.asar/node_modules/@meetfranz/ui/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:310:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:523:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:874:27)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/Ferdi/resources/app.asar/components/ui/Modal/index.js:1:404)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)


```

**Comment by kris7t** [comment]
@nullket So latest nightly is working, but latest beta doesn't? That's mighty strange...

**Comment by nullket** [comment]
The latest nightly is [release 48](https://github.com/getferdi/nightlies/releases/tag/v5.6.0-nightly.48) which was issued before your docker electron builder fix. This nightly works perfectly fine. Building the `develop` branch at https://github.com/getferdi/ferdi/commit/1886c8abed32e33f0f547c069c674b79279cf931 (including a `git submodule update`) with docker results in the `ui` missing error shown above. 

I could build the newest nightly branch (with the docker build environment fixed) and compare that particular package (make a package diff as shown above) if you could release a newer nightly which at least includes the commit with the docker build changes?

**Comment by kris7t** [comment]
Ah, okay, so the issue is still with the Docker build only.

I'll keep investigating, then. I'm not sure why the newer nightlies are not available for download, CI seems to build them fine and then publish to Github...

**Comment by nullket** [comment]
I thought maintainer had to do this manually, taken from the readme
> Nightly releases are automatically triggered every day (details) and available in getferdi/nightlies. Maintainers still need to manually publish the draft releases as pre-releases for now.

**Comment by kris7t** [comment]
Yeah, but I don't have the privileges to approve them (and don't know why haven't anyone with the appropriate privileges approved them).

**Comment by kris7t** [comment]
@nullket You can try https://github.com/getferdi/nightlies/releases/tag/v5.6.0-nightly.53 now

**Comment by vraravam** [comment]
@nullket - FYI, the Docker builds are _very experimental_: I was trying to build the linux artifacts on my macos, and though it seemed to work in the beginning, of late, its been failing consistently for the past few weeks. Since we had other issues to focus on, we haven't had a chance to take a look at this. Maybe the Docker builds can be reviewed once more (after we release `5.6.0`). In the meantime, if you can contribute a fix, we would really appreciate it.

**Comment by nullket** [comment]
@vraravam I totally agree with you! Unfortunately, I don't know anything about JavaScript and Electron and therefore thought building with docker might be the easiest way to...
- ... A) use your development progress (as I have some custom services which are not working very good and I hoped newer electron versions might fix those but the nightly builds were broken)
- ... B) tinker a bit with JavaScript/Ferdi 

Anyway, with the nightly builds working I can perfectly live without docker. So yes, you should totally focus on 5.6.0 (and more important stuff like the external url handling/clicking etc.)!! 

@kris7t Nonetheless, just for the record: I have build the latest commit on the nightly branch with docker (still not launching due to the `ui` lib missing) and ran another package diff: 
- Mostly only the .tar.gz of the recipes are different 
- The binaries of the tarballs differ only by `0.01%` (I will check the content later). 
- Yes I made sure the recipe submodule is at https://github.com/getferdi/recipes/commit/19a224623d8b4b2302994ccab050b463d0ee817d as specified in nightly 53 in the nightly branch at https://github.com/getferdi/ferdi/commit/c587a3466d0fa3badee0944bb0e42580ccb23e96
- Non relevant differences: The nightly "deb change log" contains a build number (?) after the nightly version number, the install size is a bit different (due to the differences in all the tarballs of the recipes)  
- I doubt the difference in the recipes causes this error, but everything else is the same...

**Comment by vraravam** [comment]
yes, I'm ignoring the `*.md` as part of the `.dockerignore` file. So, when the recipes and other code is copied into the Docker context, those will be "lost".

**Comment by vraravam** [comment]
@nullket - I just noticed that `@meetfranz/theme` was missing in the `package-lock.json` (not sure why this was not found earlier - because this file is auto-generated. Anyways, I have committed this into the `develop` branch. If you are building from source, please pull the latest and try this again. If not, please wait for the nightly builds to check this out (approximately another 20 hours or so)

**Comment by nullket** [comment]
@vraravam I have build your https://github.com/getferdi/ferdi/commit/45bfd3445e7636fa3605f08e960f121793ae63f2 commit using docker and the issue persists with the missing `@meetfranz/ui/lib/index.js` module. Btw. I double checked this with the .appimage and the same issue occurs there too. I wait for the next nightly but I assume that one will (still) work.

**Comment by vraravam** [comment]
@nullket - sorry to take so long to get back to you on this. Since another user also reported the same issue, (and since the docker builds are now working on my local mac!), I was able to find a fix. I still don't know if ferdi starts up (since I am not on linux), but the missing resource file should be taken care of. Please follow [this PR](https://github.com/getferdi/ferdi/pull/1616) for this.
