### ISSUE TITLE
Immediately after adding a new service, keyboard shortcut to switch to that service not working

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#204]
**Describe the bug**
Immediately after creating a new service, use the `Cmd+<number>` shortcut to move to the first service. Then try to use the corresponding <number> to switch back to the service that was just added - it will not switch to that service. This service-switching though works correctly after restarting Ferdi.

**To Reproduce**

1. Create 1 service in Ferdi
2. Close and restart Ferdi
3. Create a 2nd service
4. Type `Cmd + 1` - focus should switch to the 1st service
5. Type `Cmd+2` - focus will remain on service 1
6. Restart Ferdi
7. Now you will be able to toggle focus between the 2 services by using the appropriate `Cmd+<number>`

**Expected behavior**
At step 5 above, the focus should have switched to the newly added service

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser Ferdi
- Version 5.3.3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vantezzen** [comment]
Related to #147. The menu bar doesn't update correctly when Ferdi changes its content.

**Comment by vantezzen** [comment]
Can't reproduce on macOS Catalina and Ferdi 5.4.3.

**Comment by vraravam** [comment]
reopened

**Comment by vraravam** [comment]
I haven't checked this recently - but, don't think this was specifically
fixed.

**Comment by webserviceXXL** [comment]
The problem still exists. Had the same while configuring Ferdi today. It seems that Ferdi can't quick switch between workspaces which causes that problem. After adding a news service it's listed in the QuickSwitcher also if the app isn't in that Workspace.

**Comment by vraravam** [comment]
Closing - since this started working at some point in time.

**Comment by axhamre** [comment]
I experienced this as well. Below is what happened to me. I'm using a Mac (11.6).

1. I added two instances of Gmail and one instance of Notion. Could not toggle between services with CMD+1, CMD+2 etc.
2. Restarted Ferdi a couple of times, to no avail.
3. Removed one insance of Gmail, it now started to work.
4. Re-added the second instance of Gmail, and toggling still works.
