### ISSUE TITLE
Blue bar when using horizontal layout

### ISSUE THREAD

**Issue by jblion** [getferdi/ferdi#2256]
Hi, 

**OS**: Linux Mint 20.2 + Cinnamon
**Ferdi** : Flathub 5.6.2 then 5.6.3

When using horizontal layout, I have a useless blue bar. 
Depending on the icon's size or the sidebar's size, the blue bar increases or decreases... but never disappears.
Adding / removing service's name has no effect on the blue bar.

Here is a screenshot: 

![bug_ferdi](https://user-images.githubusercontent.com/15637996/142588280-797a7831-310f-403d-a4eb-a1199b68c952.png)

(for confidentiality purposes, I deleted some parts of my screenshot. A blur could be undone, not a delete :) )

**Comment by noraj** [comment]
## Normal width - Vertical

![image](https://user-images.githubusercontent.com/16578570/145211235-5d113a47-3863-4c61-806f-6a381440c793.png)

## Normal width - Horizontal

![image](https://user-images.githubusercontent.com/16578570/145211298-6e06954d-ea7d-49cb-948a-2340da347b43.png)

## Normal width - Horizontal - Display service name

![image](https://user-images.githubusercontent.com/16578570/145211465-76c3a12c-9da3-49ee-b81f-15d734d24881.png)

## Slim width - Horizontal - Display service name

![image](https://user-images.githubusercontent.com/16578570/145211534-c9028e7a-ee52-4c6f-b49e-aa7f48782c51.png)

## Very slim width - Horizontal - Display service name

![image](https://user-images.githubusercontent.com/16578570/145211597-fd5f2c99-3044-4b3e-8423-6fd79e6079f6.png)

## Extremely slim width - Horizontal - Display service name

![image](https://user-images.githubusercontent.com/16578570/145211693-9c856f6b-d427-4f9f-b807-1de57d33a7b3.png)

## Extremely slim width - Horizontal

![image](https://user-images.githubusercontent.com/16578570/145211798-9aa36199-1155-456b-9ad2-e6e11f8c5117.png)

## Questions

- Where does this ugly and useless purple bar come from on horizontal style?
- Why the ugly and useless purple bar grows bigger the slimmer the horizontal bar is only when service names are displayed and stay at a fixed hight when they are hidden ?

**Comment by vraravam** [comment]
This has been fixed by #2179 - please use one of the new nightlies from https://github.com/getferdi/ferdi/releases

**Comment by noraj** [comment]
> This has been fixed by #2179 - please use one of the new nightlies from https://github.com/getferdi/ferdi/releases - once you confirm, then we can close this ticket.

Thanks for the information. I'll wait for 5.6.4 release.

**Comment by jblion** [comment]
![ferdi-25](https://user-images.githubusercontent.com/15637996/145220498-39a520a5-3864-4b4e-bf19-d2594a09d154.png)

Ths issue is still present with the nightly-25 version.

**Comment by jblion** [comment]
Hi, 
I have a different behaviour with the -34 version:
The bar (now grey, depending on my theme) has always the same height (with extra small / extra wide sidebar)
Labels are messed up

![ferdi-34](https://user-images.githubusercontent.com/15637996/146286472-61f21afe-9978-4bcd-a87f-dab14279b998.png)

**Comment by reggermont** [comment]
With official 5.6.4 version, bar is now black. Better but still annoying 😄 

![image](https://user-images.githubusercontent.com/14902909/146597195-d4a4244c-373f-4253-a388-346698511240.png)

**Comment by vraravam** [comment]
I am guessing that this might be due to the space "reserved" for rendering the service name. Could you please turn on that option, and add a new screenshot with that turned on?

**Comment by jblion** [comment]
> I am guessing that this might be due to the space "reserved" for rendering the service name. Could you please turn on that option, and add a new screenshot with that turned on?

Who are you talking to ?
Which option are U talking about ?

Sidebar is completely messed up with 5.6.4. Just unusable ! This release should have not been released !

* Extremely thin + normal icons: 

![image](https://user-images.githubusercontent.com/15637996/146637691-3f06bc06-099e-4995-a898-5155a92eda7b.png)

**Without labels**
![image](https://user-images.githubusercontent.com/15637996/146637706-8c1f094d-72ba-4d49-97ea-5591f3900fe5.png)

* Normal + normal icons

![image](https://user-images.githubusercontent.com/15637996/146637758-d1670529-ba3a-48da-afe6-1c2d56a53701.png)

**Without labels**
![image](https://user-images.githubusercontent.com/15637996/146637781-2a79a67f-0909-4fd6-8c59-a6a73983c597.png)

* Very Slim sidebar + Very small Icons

![image](https://user-images.githubusercontent.com/15637996/146637815-df652e34-2f2c-4fad-a57f-7c58af5b6b2f.png)

**Without labels**
![image](https://user-images.githubusercontent.com/15637996/146637829-9b5a04ad-460d-41a8-a6ed-8d30e539c725.png)

**Comment by kytwb** [comment]
Let's address this in #2379.

**Comment by noraj** [comment]
I think the issue in #2256 (here) and the feature request in #2379 are different even if both are about the sidebar.
