### ISSUE TITLE
Slack service missing Slack Workspace's custom icon 

### ISSUE THREAD

**Issue by mastercko** [getferdi/ferdi#290]
**Describe the bug**
When signing in to a Slack workspace on Ferdi, it shows up on Ferdi's Service Bar (on the left side of the Ferdi window) with the default Slack icon (rainbow "#") and not that Slack workspace's specific custom icon.

**To Reproduce**

1. Add a new service
2. Select Slack
3. Follow the normal process to add a Slack workspace (which has a custom icon defined in its settings) 
4. Login to said Slack workspace
4. Observe the new Slack service listed on the Service Bar on the left side of the Ferdi window

**Expected behavior**
The icon for Slack in the Service Bar on the left side of the Ferdi window should use the given Slack workspace's specific custom icon.

**Desktop information**
- OS: Windows 10
- Version 10.0.18363 Build 18363

**Additional context**
This is a 100% reproducible error on my installation from multiple Slack accounts. Completely quitting and re-starting Ferdi does not fix the issue. The only workaround I have found is to download the icon for the Slack workspace from Slack's web page and manually set the icon for the Slack service in Ferdi.

**Comment by vantezzen** [comment]
This looks to be a bug in [the Slack recipe](https://github.com/meetfranz/recipe-slack) or Franz itself as this problem to exist in Franz too (https://github.com/meetfranz/franz/issues/1566).

It looks like client-code setting the icon works as expected (as can be tested with this code:
```JavaScript
ferdi.actions.service.updateService({
	serviceId: ferdi.stores.services.active.id,
	serviceData: {
		customIconUrl: "https://github.com/getferdi/ferdi/raw/develop/build-helpers/images/icon.png" 
    },
	redirect: false,
})
```
) and the webview code getting the code also seems to get the URL correctly (as can be seen when executing [the function](https://github.com/meetfranz/recipe-slack/blob/master/webview.js#L4-L33) manually). I suspect that there might be a problem with the communication between the two?

Related:
https://github.com/meetfranz/franz/issues/1566
https://github.com/meetfranz/franz/issues/1594

**Comment by grmon** [comment]
Same here:
Ferid 5.4.1-beta.3
macOS 10.14.6

**Comment by kytwb** [comment]
@mastercko @grmon The team icon isn't available anymore on the login page, so the service will properly retrieve the team icon only when saving the service while already logged in the Slack.

1. Add Slack service
2. Log in Slack
3. Edit Slack service
4. Save Slack service

This is the work-around I found at the moment.

**Comment by grmon** [comment]
Hey @kytwb,
where would I have to edit the service to change it? I tried the Ferdi Service setting but nothing changed.

**Comment by kytwb** [comment]
@grmon I noticed you're on https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.3; you would need to upgrade to https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.4 or above first as it includes the update to the Slack recipe that fixes the getTeamIcon function:
https://github.com/getferdi/recipes/commit/2491ea3c11de71391cd333cfc375576232d64cba#diff-a8dbcea6f48616265b870277bcab6f24.

Forget about the workaround I mentioned earlier, I got confused myself.

**Comment by kytwb** [comment]
Closing for now as I have been able to confirm it works in newer versions:

<img width="310" alt="Screen Shot 2020-02-25 at 4 09 27 AM" src="https://user-images.githubusercontent.com/412895/75212004-eb68c400-5785-11ea-965d-9c80dbeab35b.png">

**Comment by kytwb** [comment]
@grmon Did you give a try to a newer version? We just released [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2).

**Comment by jrpeck1989** [comment]
I still have this issue on Windows 10, version 5.4.4-beta.3.

![image](https://user-images.githubusercontent.com/19979191/77657435-346e8c80-6f6d-11ea-8ee5-2d109cae069f.png)

Although some Slack channels the icon does display correctly, but not most.

**Comment by ygrange** [comment]
OSX 10.15.3 with  5.4.4-beta.3 still has an issue with custom slack icons. Some of them won't load while others do. I don't really know what the difference between the two is though...

**Comment by ygrange** [comment]
Updating this issue: 5.5.0 still leaves several slack custom icons unloaded and shows me the slack default icon.

Also, all icons disappear on startup time to reappear after a while, but I can sort of live with that.
