### ISSUE TITLE
Can't open links in Gmail (popup blocker)

### ISSUE THREAD

**Issue by Dunkh4n** [getferdi/ferdi#321]
**Describe the bug**
When i left click on a link in gmail, i have a popup telling me that i may have a popup blocker thus not to been able to open the browser.
I can however right click on the link, select 'open link in browser' in the context menu and the default browser open (or 'copy link' and past it directly in my browser)

**To Reproduce**
click on a link in any mail in gmail

1. Go to a mail
2. Click on a link

**Expected behavior**
open the page in my default browser

**Screenshots**
![ferdi-bug-popup-blocker](https://user-images.githubusercontent.com/22644499/73015576-964f3080-3e1c-11ea-9662-4a9aa3a6bee7.png)

**Desktop (please complete the following information):**

- OS: Win 10 pro
- Browser : Ferdi
- Version : 5.4.0

**Additional context**
I have this bug since the auth problem cited in #264 and made the change on my UA witch is now 
`module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
      return 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0';
    }
  };
`
But the problem happen even with every other UA provided in #264 
I do not have any problems with other services (left click open the browser normaly

**Comment by vantezzen** [comment]
Does this happen in all mails? I suspect this could be something similar to what happened in #36 with Skype (Skype used an unusual technique to open links). I am currently looking into if I can find what technique GMail is using to open links - if anyone wants to search too and share their finding they are welcome to.
Searching for the error message inside GMail's sources shows that this messages gets thrown inside a highly obfuscated "Wic.prototype.openWindow" function.

**Comment by Dunkh4n** [comment]
yes, it's happen in all mails..

**Comment by vantezzen** [comment]
Ok, I tried debugging how this works but I can't get the function mentioned above to trigger - no matter what link I click it always just uses the default link behaviour - so I can't debug this problem any further.

**Comment by mokipedia** [comment]
I switched today from Franz and experience the same issue. I also had the same login problem and had to change the user agent string. I have 2 Gmail services and both have this problem. Happy to provide more info if need be.

**Comment by mokipedia** [comment]
i just fixed my issue by switching the user agent string again, this time to:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36`
(which is what my current chrome is sending out).
Then I restarted Ferdi, just to make sure (seems like reloading multiple times may or may not shield success, so I just restart it when I change a recipe)

**Comment by nicosebastian93** [comment]
@mokipedia worked for me as well. Thanks!

**Comment by vantezzen** [comment]
The User agent changes will also be shipped with Ferdi 5.4.4 automatically - so you won't have to change that manually.

**Comment by Dunkh4n** [comment]
@mokipedia worked for me as well. Thanks!

**Comment by kytwb** [comment]
Linking to https://github.com/getferdi/ferdi/issues/264 for reference.

**Comment by lisaq** [comment]
As mentioned in #264, I am having this issue now after installing  and reinstalling 5.4.4.
I did not notice it happening until this last week, around the same time I upgraded to Mac OS 10.15.3.

**Comment by kytwb** [comment]
I'm also experiencing this.

**Comment by mokipedia** [comment]
My fix still works, as gmail seems to not like firefox too much. However Franz' fix for dynamic chrome version looks promising (beta)

**Comment by mokipedia** [comment]
Updated to 5.5.0-gm today and the service reloaded. Having the same problem again.
Fix from above still works though.

**Comment by lupalby** [comment]
I'm also having the same issue. I had it with 5.4 betas, as well as the 5.5.0-gmx, and still now the the official 5.5.0

**Comment by mundo03** [comment]
workaround: Control + click (or whatever equivalent is on osX) will open the link in a browser with no issues.

**Comment by CptDinosaur** [comment]
Same issue here!

**Comment by jrpeck1989** [comment]
I have the same issue.

**Comment by boekkooi-fresh** [comment]
I had the same issue on `Ubuntu 18.04.4 LTS` running installed version `ferdi_5.5.0_amd64.deb`.

Changing the code in `~/.config/Ferdi/recipes/gmail/index.js` to the following fixes my issue (the new useragent is the once used by chromium).
```Javascript
var os = require('os')

module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
      return "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.163 Chrome/80.0.3987.163 Safari/537.36";
    }
  };
```

**Comment by danielleos** [comment]
Just upgraded to latest 5.5.0 on macOS 10.14.6 - still happening on gmail - fix above works, but thought this was going to be released as standard from 5.4.4 ?
<img width="438" alt="Screenshot 2020-05-02 at 12 50 31" src="https://user-images.githubusercontent.com/16842000/80863338-8775e680-8c73-11ea-8355-0464275e3b07.png">

**Comment by ray-odoo** [comment]
Using:

![image](https://user-images.githubusercontent.com/41073831/80994390-7357f380-8df1-11ea-9b6b-16b2f2165d29.png)


For those using Windows, the same fix works, but it is a different location and a slightly different file:

Location: 
C:\Users\[your user here]\AppData\Roaming\Ferdi\recipes\gmail

File:
var os = require('os')

module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
      if (os.platform() == 'linux')
        return "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
      else
        return **"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.163 Chrome/80.0.3987.163 Safari/537.36"**;
    }
  };

**Comment by tnaseem** [comment]
Thank @ray-odoo. That fixed it for me on Windows, running v5.5.0.

**Comment by llabusch93** [comment]
Yep 5.5.0 on Linux, still having the issue. Is there a plan to fix it in the next release, so non tech people, who can't follow the workaround patch benefit from it as well?

**Comment by mahadevans87** [comment]
I have pushed a fix in the recipes which can be viewed here https://github.com/getferdi/recipes/pull/194
. Till the PR gets merged, replace the recipe's index.js file with [this](https://github.com/getferdi/recipes/blob/c15c01db45bd912e4f0daa48dab72633be761b29/uncompressed/gmail/index.js)

**Comment by Tulosi** [comment]
Still an issue on Ferdi 5.5.0 on Mac. Non tech savvy dumlock here hoping this gets fixed in the normal release asap.

**Comment by webserviceXXL** [comment]
Have the same problem, too. Mac with Catalina 10.15.5 (19F101) and Ferdi Version 5.5.0 (5.5.0.2116).

**Comment by kabronero** [comment]
Same problem here. Catalina and last Ferdi version.

**Comment by brunofunnie** [comment]
Same issue here (Ferdi 5.5.0 on Ubuntu 20.04), although pressing and holding ctrl while clicking open the link.

**Comment by twhiting9275** [comment]
Same problem as others. Win10, ctrl-click opens these for me though.
Using the proposed fix seems to work, too

**Comment by webserviceXXL** [comment]
The solution posted by @boekkooi-fresh (Linux) and @ray-odoo (Windows) is also working for Mac.👍 

On Mac, the path for the file is: `/Users/$USER/Library/Application Support/Ferdi/recipes/gmail/index.js`

```
var os = require('os')

module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
      if (os.platform() == 'linux')
        return "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
      else
         return "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.163 Chrome/80.0.3987.163 Safari/537.36";
    }
  };
```

**Comment by carsondarling** [comment]
For me, using the solution posted above broke keyboard shortcuts while composing emails in Gmail. A working fix for me, is below.

```javascript
var os = require('os')

module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
      if (os.platform() == 'linux')
        return "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
      else
        return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
        // original
        // return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0";
    }
  };
```

My guess is that by adding in `X11; Linux x64_64`, Gmail binds shortcuts to `Ctrl` instead of `Cmd`.

**Comment by dzg** [comment]
Mac 5.5.0, I get the "Grrr" alert on Gmail links. I will try the patch mentioned above.

**Comment by patrickrushton** [comment]
5.6.0-beta.2 on Mac, Gmail links open in a popup, with or without the patch from @carsondarling 
My preference would be for links to open in my default browser.

**Comment by mokipedia** [comment]
> 5.6.0-beta.2 on Mac, Gmail links open in a popup, with or without the patch from @carsondarling
> My preference would be for links to open in my default browser.
Not related to this bug, see #842

**Comment by aphexcx** [comment]
I'm running into this too on 5.5.1. I don't want to deal with patching all of my services manually (I use 6 different gmails and gcalendars and google keeps etc) so I'll switch back to Franz for now. Hopefully this is fixed soon!

**Comment by mokipedia** [comment]
Hi @aphexcx, understandable. However you patch the recipe, not the service. So 1 change per type (gmail, gcal, keep) and then restart ferdi should do it.

**Comment by stevengliebe** [comment]
Not sure if #942 is a duplicate. I only experience the popup error when clicking the print or new window icon in Gmail. None of the workarounds here resolve it.

**Comment by amykluber** [comment]
I'm getting this error as well on version 5.5.0 .. Mac Catalina.

**Comment by zzamboni** [comment]
@carsondarling's solution fixed the problem for me on macOS Catalina, Ferdi 5.5.0.

It also fixed another very weird issue I was having: when typing a message in Gmail using my external Bluetooth keyboard, pressing the Command key (labeled Alt on the keyboard, but configured on my system to act as Command) would indent the text, which made it impossible to copy/paste or to even switch applications without messing up the message. When using the laptop keyboard, everything worked fine. With the change suggested above, this problem is also gone, to my great relief :)

**Comment by nevvkid** [comment]
Hi! Is there a solution to be able to click links on latest MacOS and Windows (10) ? I can't figure out anything else than copying of the links to chrome... which breaks usability.

**Comment by jottr** [comment]
Is anyone actively working on a fix for this issue?

**Comment by zzamboni** [comment]
@nevvkid @jottr in the meantime, you could try @carsondarling's workaround posted above. It completely fixed the problem for me: https://github.com/getferdi/ferdi/issues/321#issuecomment-668207379

**Comment by jottr** [comment]
Thanks @zzamboni. 
I'd like to squash this bug for good - before I start working on a fix, I'd like to know if someone else is already working on one.

**Comment by mahadevans87** [comment]
@jottr I was working on this previously. I shall take this up if you haven't started

**Comment by Saboteur777** [comment]
This happened again to me on Linux with Ferdi 5.5.0.

Changing the string user agent string to `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36` fixed the issue (for now): 

```
var os = require('os')

module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
      if (os.platform() == 'linux')
          return "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"
      else
        return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
        // original
        // return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0";
    }
  };
```

**Comment by vantezzen** [comment]
https://github.com/getferdi/recipes/pull/194, which should have fixed this issue, was released with Ferdi 5.6.0-beta.3 or above. We will hopefully release 5.6.0 soon so this fix will be shipped with it.

**Comment by heysimo** [comment]
Hi,

I'm sorry, but beside having the issue everyone is describing, I have no idea where this code has to be put.
I did try to google, but I don't know where to start as it is unclear to me if I have to put the code in Ferdi or in Chrome.

Can anyone please explain or maybe give a proper link?
Hopefully this might help others, too. tnx!

**Comment by mokipedia** [comment]
Hi @heysimo,
it is fairly easy to understand once you get the hang of it:
- Ferdi is an electron app, which is basically a Chrome wrapper inside a Windows / Mac / Linux Application.
- Ferdi is written in Javascript and you can read and edit its files. For your purposes, you want to edit a 'recipe', which is basically a sort of configuration file(s) for each service Ferdi knows.
- They are found, depending on your OS here:
  - Mac: ~/Library/Application Support/Ferdi/recipes/
  - Windows: %appdata%/Ferdi/recipes/
  - Linux: ~/.config/Ferdi/recipes/
- In this folder, you will find recipes for gmail, whatsapp and more. Go to the recipe you want to edit and look at the JavaScript files you see there (should be 2).
  - index.js -> includes transformations and configs for the service itself, like user-agent, ... (This is the file you are looking for)
  - webview.js -> hooks into the content of the service itself, like gmail and whatsapp and adds functionality like: link behavior, unread count in Franz/Ferdi, adds css if wanted, ..

**Comment by heysimo** [comment]
> Hi @heysimo,
> it is fairly easy to understand once you get the hang of it:
> 
> * Ferdi is an electron app, which is basically a Chromium wrapper inside a Windows / Mac / Linux application. It has nothing to do with Chrome Browser, other than they both use Chromium to run JS and Render Websites under the hood.
> * Ferdi is written in Javascript and you can read and edit its files. For your purposes, you want to edit a 'recipe', which is basically a sort of configuration file(s) for each service Ferdi knows.
> * They are found, depending on your OS here:
>   
>   * Mac: ~/Library/Application Support/Ferdi/recipes/
>   * Windows: %appdata%/Ferdi/recipes/
>   * Linux: ~/.config/Ferdi/recipes/
> * In this folder, you will find recipes for gmail, whatsapp and more. Go to the recipe you want to edit and look at the JavaScript files you see there (should be 2).
>   
>   * index.js -> includes transformations and configs for the service itself, like user-agent, ... (This is the file you are looking for)
>   * webview.js -> hooks into the content of the service itself, like gmail and whatsapp and adds functionality like: link behavior, unread count in Franz/Ferdi, adds css if wanted, ..
>   * there are other files in there too, you can read about more it, for example here (googled it): https://blog.jakelee.co.uk/super-simple-guide-to-adding-a-new-ferdi-service-recipe/

Can't thank you enough, really.
Fixed the issue straight away.
Amazing!

**Comment by chauhanankit83** [comment]
I just found out the below code to fix the popup blocker issue.

var os = require('os')

module.exports = Franz =>
class Gmail extends Franz {
overrideUserAgent() {
if (os.platform() == 'linux')
return "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
else
return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
// original
// return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0";
}
};

**Comment by onechaiplease** [comment]
I just found out the below code to fix the popup blocker issue.

var os = require('os')

module.exports = Franz =>
class Gmail extends Franz {
overrideUserAgent() {
if (os.platform() == 'linux')
return "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
else
return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
// original
// return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0";
}
};

**Comment by nmrshll** [comment]
Same problem here on 5.5.0 for Mac. @carsondarling 's fix worked great though, so thanks !

**Comment by s0undt3ch** [comment]
Same problem here on 5.5.0 for Linux.

**Comment by mbootsman** [comment]
Using the 5.6.0 beta 5 here on Ubuntu.
Left click doesn't do anything.
Middle click, and CTRL click works, but hey, that's a workaround, not a solution.

**Comment by rekire** [comment]
To be honest, this is a show stopper for me. I just installed it and added gmail and slack and both plugins do not work out of the box. To be honest I do not really care about the mentioned workarounds here. Why is that not yet fixed? This bug is more then one year old.

**Comment by mbootsman** [comment]
> To be honest, this is a show stopper for me. I just installed it and added gmail and slack and both plugins do not work out of the box. To be honest I do not really care about the mentioned workarounds here. Why is that not yet fixed? This bug is more then one year old.

I switched to Franz, and supported them with a paid account. At least clicking a link works :wink:

**Comment by daniel-vera-g** [comment]
> To be honest, this is a show stopper for me. I just installed it and added gmail and slack and both plugins do not work out of the box. To be honest I do not really care about the mentioned workarounds here. Why is that not yet fixed? This bug is more then one year old.

Can only agree. I would use the app, but not having such simple features working is a blocker.  
The issue is over a year old and the last stable release a year ago. The project seems active, so I'll keep an eye on it.

**Comment by jottr** [comment]
I’ve also moved away from Ferdi because mailto-link handling has been broken on most services.
This is a serious UX bug.

**Comment by kishaningithub** [comment]
To circumvent this, i am actually doing a right click. This gives me the open to press "open link" this opens the link in my default browser(firefox)


<img width="253" alt="Screenshot 2021-04-27 at 10 45 29 AM" src="https://user-images.githubusercontent.com/763760/116188853-b1a69b00-a745-11eb-9149-2e63e9aea800.png">

**Comment by brockhicks** [comment]
Same issue for me and listed solutions are beyond my technical skills -- will this be fixed in an update? I'm running 5.5.0

I'm in the same boat as many commenters here -- I am constantly needing to click links in my gmail and other services so need this to work out of the box or have  a simple, non-coding solution.

![image](https://user-images.githubusercontent.com/19536706/117338545-90376480-ae53-11eb-9b8b-d4bf347b5088.png)

**Comment by Tulosi** [comment]
Given that this is apparently fixable, as shown above, but has continued to be an unaddressed issue for well over a year, I think it's safe to say Ferdi isn't really getting the attention it needs.

Is the project effectively dead / unmaintained?

**Comment by jottr** [comment]
I'm sure people would be willing to help by creating a PR with a fix. 
The core team just needs to get involved in the discussion a provide some guidance and become more responsive.
Why should I spend my time working on a fix, if I won't even know if my PR will get accepted/merged?

**Comment by fredcallaway** [comment]
Hit the same problem. I'm fine editing config files, but  ~/.config/Ferdi/recipes/gmail/index.js doesn't exist for me. There's no ~/.config/Ferdi at all in fact. Could the config directory have been moved in a recent update?

**Comment by vraravam** [comment]
@fredcallaway - please see the location based on your OS in [this section](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help).

**Comment by vraravam** [comment]
> I'm sure people would be willing to help by creating a PR with a fix.
> The core team just needs to get involved in the discussion a provide some guidance and become more responsive.
> Why should I spend my time working on a fix, if I won't even know if my PR will get accepted/merged?

@jottr - Please call out for help in the gitter channel (link in the badges section in `README.md`. I have just joined the contributors list a month ago - and I found at least a couple of contributors quite responsive over there.

**Comment by ccamejo-dev** [comment]
> Using:
> 
> ![image](https://user-images.githubusercontent.com/41073831/80994390-7357f380-8df1-11ea-9b6b-16b2f2165d29.png)
> 
> For those using Windows, the same fix works, but it is a different location and the contents of the file are slightly different:
> 
> Location:
> C:\Users[your user here]\AppData\Roaming\Ferdi\recipes\gmail
> 
> File:
> var os = require('os')
> 
> ```
> module.exports = Franz =>
>   class Gmail extends Franz {
>     overrideUserAgent() {
>       if (os.platform() == 'linux')
>         return "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
>       else
>         return "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3987.163 Chrome/80.0.3987.163 Safari/537.36";
>     }
>   };
> ```
> 
> (change the SECOND return line to match what is above - the code above is the file AFTER I made the changes).

Thanks so much @ray-odoo ! This still working on v5.5.0 for Windows.

**Comment by fredcallaway** [comment]
https://github.com/getferdi/ferdi/issues/321#issuecomment-668207379 worked for me too. It seems like that has worked for a lot of people, so I wonder if the fix is as simple as pasting that snippet into master? Or would/could this break things for people who it works for now?

**Comment by vraravam** [comment]
This is now fixed by https://github.com/getferdi/ferdi/pull/1474 - which has just been merged! Please pull and rebuild from source, or wait for tonight's nightly build.

**Comment by vraravam** [comment]
Please try with the [latest nightly](https://github.com/getferdi/nightlies/releases/tag/v5.6.0-nightly.55). Closing this ticket since its fixed.

**Comment by Tulosi** [comment]
The nightly build is now opening clicked links in some kind of internal browser, rather than the system default browser.

Is there a way to change this behavior? I have not found one via the settings.

![2021-06-01 19_44_33-Microsoft Store](https://user-images.githubusercontent.com/68391545/120411473-1db28b00-c312-11eb-900c-1f963f7c56c3.png)

**Comment by jottr** [comment]
@vraravam I don't consider this issue fixed. Links are opened in Ferdi window instead of the Desktop browser.
It's nice that we have #1474 as a temporary workaround, but this is not a solution that warrants closing this issue.
Please reopen.

**Comment by vraravam** [comment]
@jottr - i have reopened the issue. But, I don't find a solution that'll work for all usecases. Let me describe:
I have signed up for gmail as a service within Ferdi. I get an email which has a link. In the web view, I also see links for the different tags/folders that I have in my gmail account. On the top right, I see the settings gear icon and some more links that allow me to manage my account and navigate to the other services like gDrive, gCalendar, etc. All of these are links (including the ones that appeared within the email that I am previewing), but there's no consistent way to handle the behavior when the user clicks on any of them. Google, classifies them as:
1) links that need to open in the same view
2) links that need to open in a new browser window/tab.

Now, one might say that any links (`a href`) that have a `target` attribute can be opened in a new browser window, whereas ones that don't, could be opened within Ferdi. If so, that person would be only partially correct: there are some services that also differentiate between `target=_blank` vs `target=new` vs `target=blank`, etc.

We are faced with a dilemma here - a single solution that works consistently across all supported services - this is not possible with the volunteering that we do now. IF you or anyone can come up with a simple enough strategy - and help implementing it, we would really appreciate it.

**Comment by adamlove86** [comment]
Hi all, 
I'm on Ubuntu and have been having this issue for as long as I can remember. Right click and Open Link works, however.
Is it possible to just swap (or have an option in the settings to swap) the command that runs with right click Open Link, with the current left click command?
That'd solve all my problems!

**Comment by vraravam** [comment]
@adamlove86 - as I have described above, the problem is that each website treats links differently with/without `target` attribute AND different values for this attribute if its present. On top of that, the users of Ferdi are themselves split on the default behavior.

I think your suggestion is quite valid (in fact I have been thinking along the same lines - have a simple dropdown in the preferences, and allow the user to choose the default behavior of left-clicking on links).

We can take this under consideration for the next major release of ferdi, but atm, we are trying to release the next beta version asap.

**Comment by sad270** [comment]
Works good for me with `5.6.4-nightly.12` on `macOS Big Sur`
