### ISSUE TITLE
Slack notification count always set to 1 even without mentions

### ISSUE THREAD

**Issue by tobilen** [getferdi/ferdi#348]
Exact same bug as in franz: https://github.com/meetfranz/franz/issues/1715

--------------------------------

> I was used to see in Franz badges for slack workspaces a single dot when there are unread messages in any channel, and a number when there are unread mentions, reporting the total of unread mentions.
> Now I always see numbers: when I have any amount of unread messages in channels without direct mentions, Franz shows "1" instead of the red dot, confusing me because I think I've mentioned while I'm not.
> 
> ### Expected Behavior
> In the service's badge, I should see:
> 
> Unread messages without direct mentions to me (nor @here nor @channel): red dot.
> Unread messages directed to me (including @here or @channel): unread direct messages count
> 
> ### Current Behavior
> In the service's badge, I see:
> 
> Unread messages without direct mentions to me (nor @here nor @channel): the number "1" (wrong)
> Unread messages directed to me (including @here or @channel): unread direct messages count (right)
> 
> ### Screenshots (if appropriate):
> As you can see in the screenshot, the selected service badge reports "1" but I have no mentions in any channel.
> ![Screenshot 2019-12-06 at 19 18 13](https://user-images.githubusercontent.com/1880350/70346310-5af1a600-185e-11ea-94b3-fcfe3053ee01.png)
> 
> ### Steps to Reproduce (for bugs)
> 1. Open Franz, add a slack service.
> 2. Mark everything as read
> 3. Wait for any new message in any channel without direct mention
> 4. See that the service badge shows "1"
> 
> ### Context
> I think the context should be pretty clear by now.
> 
> ### Your Environment
> * Franz Version used: Version 5.3.3 (5.3.3.1582)
> * Operating System and version: macOS Mojave 10.14.6 (18G103)

**Comment by kytwb** [comment]
Related to https://github.com/meetfranz/recipe-slack/pull/13 and seems to have been fixed in Ferdi by @vantezzen via https://github.com/getferdi/recipes/commit/83f946f546247572a787d451ca9ec6649c600849. The fix should be available in the next release.

**Comment by vantezzen** [comment]
@kytbw Fix is originally from getferdi/recipes#39

**Comment by kytwb** [comment]
Ah my bad, went a bit fast: fixed by @Serubin 🙏 
Closing for now.

**Comment by pegasusearl** [comment]
Hello I'm in version 5.5.0 Flatpak and this issue is still happening.
Slack only. I have restart ferdi too.
![17_07-49-30_824](https://user-images.githubusercontent.com/23167087/93406665-6a585200-f8ba-11ea-9c2d-6296d4b58a19.png)

**Comment by Serubin** [comment]
Can you provide a screenshot of this issue? It's been fixed - and has stayed fixed as far as I can tell

**Comment by pegasusearl** [comment]
![17_08-29-53_674](https://user-images.githubusercontent.com/23167087/93408971-06388c80-f8c0-11ea-9562-c622911ddb79.png)

here, there are no unread messages but it shows 1 as unread.

**Comment by Serubin** [comment]
I'm unable to reproduce. Perhaps it'll resolve when you finish setting up slack.

**Comment by Jendker** [comment]
I can confirm that. Finishing "Getting started" removes the 1 count.
