### ISSUE TITLE
allow clicking on links and copying them

### ISSUE THREAD

**Issue by eadmaster** [getferdi/ferdi#354]
When i click on a link in Gmail i get the popup blocker dialog.

I also cannot copy the link since the context menu is blocked.

**Comment by kytwb** [comment]
Closing in favor of https://github.com/getferdi/ferdi/issues/354.

**Comment by kytwb** [comment]
We haven't found a work around against the popup blocker just yet, but we have fixed the context menu so that should help: https://github.com/getferdi/ferdi/pull/419. Shipping in the next release. Thanks for your patience! 🙏

**Comment by kytwb** [comment]
Fixed via https://github.com/getferdi/ferdi/issues/321#issuecomment-581141362, related to https://github.com/getferdi/ferdi/issues/264.

**Comment by kytwb** [comment]
Shipped in [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3).

**Comment by squatto** [comment]
I'm on 5.4.4-beta.3 and still can't open links in Gmail (I still get the popup blocker error). However, I do have the context menu, and if I click "Open Link" in the context menu, it opens the link in my Browser just fine (as if I had clicked the link itself).

**Comment by ray-odoo** [comment]
The solution in https://github.com/getferdi/ferdi/issues/321 worked for me today, running 5.5.0.
