### ISSUE TITLE
Keyboard shortcuts not working on macOS

### ISSUE THREAD

**Issue by lisaq** [getferdi/ferdi#362]
**Describe the bug**
Keyboard shortcuts for text have mysteriously stopped working.

**To Reproduce**

1. Go to any service (observed in Slack, Gmail, Keep, Tweetdeck, etc.)
2. Select some text
3. Use a key command (copy, paste, cut, select all, etc.)
4. Observe that nothing happens

**Expected behavior**
Keyboard commands should work as they do in any other application, ie. command+x should cut text.

**Desktop:**

- OS: macOS Catalina
- Ferdi Version 5.4.3
- Server Used: https://api.getferdi.com
- Logged into account

**Comment by kytwb** [comment]
@lisaq Are you using Ferdi's lock feature by any chance? I have found a bug with the help of @alksabobic that could lead to the Menu being empty (usually when locked) even when unlocked. The menu being empty would lead to the shortcuts to not work.

**Comment by kytwb** [comment]
We believe this has been fixed in [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2).

**Comment by lisaq** [comment]
very much appreciated, thank you :)

**Comment by fuzzy76** [comment]
This didn't solve everything mentioned in #377, despite it being closed as a duplicate of this.
