### ISSUE TITLE
Cannot load Microsoft Teams

### ISSUE THREAD

**Issue by dpkonofa** [getferdi/ferdi#475]
New user trying to move to Ferdi from Franz and, while I was able to import my Franz account and it lists all the services on the left, nothing is working. I have Microsoft Teams and Slack services only and they're all just stuck on loading. If I do get a Teams service to load, it shows my chat list but none of the messages on the right-hand side.

1. Open Ferdi. Login with Franz account.
2. Wait for services to load.
3. Continue to wait for services to load.
4. Panic.

**Expected behavior**
At minimum, expected behavior is to carry over from Franz and load services just like in that app since this is a fork.

**Screenshots**
<img width="1139" alt="Screen Shot 2020-03-17 at 12 24 05 PM" src="https://user-images.githubusercontent.com/6332378/76893807-35efd480-684a-11ea-9943-bc5e804cdd3f.png">

<img width="1139" alt="Screen Shot 2020-03-17 at 12 23 15 PM" src="https://user-images.githubusercontent.com/6332378/76893767-22dd0480-684a-11ea-95a9-c7188890f1c6.png">

**Desktop:**

- macOS Catalina
- Ferdi v5.4.3
- Server Used: https://api.getferdi.com

**Additional context**
I have attempted to remove all my services and re-add them but this doesn't change anything. Removing the Teams services has actually set me back as I can no longer get Teams to actually load.

**Comment by dpkonofa** [comment]
I've been able to get the Slack channels running by upgrading to the latest Ferdi and deleting my account and recreating from scratch but Teams services are still not loading.

**Comment by dpkonofa** [comment]
Here's what I'm getting from the Service Dev Tools:  
<img width="912" alt="Screen Shot 2020-03-17 at 1 52 22 PM" src="https://user-images.githubusercontent.com/6332378/76900437-9422b480-6856-11ea-9a00-cdd183a2215d.png">

**Comment by dpkonofa** [comment]
Reinstalled Franz and Teams is working within that app so it looks like the issue might be with Ferdi specifically...

**Comment by vantezzen** [comment]
We are sorry that you have such a bad experience switching to Ferdi - we try to make transition as easy as possible.

About MS Teams: Have you got the the login screen and logged in or does this happen even before that?

**Comment by dpkonofa** [comment]
@vantezzen - I am able to login without issue but, once the screen that says "Loading Microsoft Teams..." comes up, it just sits there until I eventually get what's in my 2nd screenshot.

**Comment by dpkonofa** [comment]
Another thing...  I have only been able to get to it twice but, occasionally, I will see the screen to download the Microsoft Teams app prior to the loading screen. It shows up briefly and then disappears.

**Comment by dpkonofa** [comment]
Is anyone able to use MS Teams currently with Ferdi? It seems like basic functionality for Services from Franz to work on Ferdi.  :-/

**Comment by doschupp** [comment]
I also have problems with MS Teams in Ferdi. The service is loaded correctly and a login works for me, but after my login new messages are not shown. Only older one.

**Comment by dpkonofa** [comment]
That's farther than I get. I've only ever gotten messages to show the first time I added the service. After that, I just get the loading screen no matter what.

**Comment by fr3nd** [comment]
Having the same issue. Going to `View -> Toggle Service Developer Tools -> Clear Storage -> Clear site data` and reloading Teams seems to fix the not receiving messages error. I usually have to do it once per day.

**Comment by kytwb** [comment]
@dpkonofa Both @vantezzen and I don't use MS Teams and unfortunately currently have no credentials to test this. We weren't able to establish an easy fix by looking at the shared logs, so it would need deeper investigation. We will see what we can do and how we can further investigate this error, otherwise anyone concerned and interested is welcome to help us find a fix for this.
Thanks for your understanding.

**Comment by dpkonofa** [comment]
I’m happy to help however I can, I’m just not even sure where to start. I’m even happy to act as a proxy to test Teams and report back, screen share, or anything necessary.

**Comment by dpkonofa** [comment]
> Having the same issue. Going to `View -> Toggle Service Developer Tools -> Clear Storage -> Clear site data` and reloading Teams seems to fix the not receiving messages error. I usually have to do it once per day.

Tried this with no success. Still gets stuck on Loading and doesn't even prompt me for a login.

**Comment by gabordewit** [comment]
> Having the same issue. Going to `View -> Toggle Service Developer Tools -> Clear Storage -> Clear site data` and reloading Teams seems to fix the not receiving messages error. I usually have to do it once per day.

This seems to work for me as well, after this change I'm able to see the ongoing chats again + able to join TEAMS meetings via the Calendar option in the TEAMS GUI.

Main issue for me was twofold:
- New notifications were shown, but loading chatwindows only showed historic conversations;
- Joining a TEAMS meeting from the calendar did not work

After clearing the data I can do both things again. Not sure if both issues need to be split from a reporting and bugfixing perspective.

**Comment by dpkonofa** [comment]
Is there a way to reset the Teams service completely besides removing it and re-adding?  I've removed it and re-added to no avail and I can't get past the panel where it says "We're sorry, we've run into an issue" no matter how many times I clear the cache, local storage, or anything else in either dev tools or dev tools for the service.  😢

**Comment by fklement** [comment]
I'm getting a slightly different error message in the console debug window then @dpkonofa 

<img width="1002" alt="Screenshot 2020-04-01 at 23 13 01" src="https://user-images.githubusercontent.coA/7302097/78187321-7f593a00-746e-11ea-9151-84a395c634b5.png">

Did anyone solve this issue by now? This is really the only thing that keeps me away from switching from "All-in-One Messenger" to "Ferdi".

**Comment by dpkonofa** [comment]
Not as far as I know.  The devs don't have Teams credentials to test so, unless someone has an org that can get them an account, I don't think there's going to be much movement here.  Thanks for the tip on "All-in-One", though.  I've been looking for an alternative since Franz works but doesn't do video/audio permissions correctly and Ferdi's Teams support is broken.

**Comment by dpkonofa** [comment]
Thanks for adding that. I’m surprised more Teams users aren’t commenting. I tried logging in with another Teams account and had the same issue so this is now reproducible.

**Comment by ckkoen** [comment]
Hi, I have the same issue when I start up Ferdi. In Franz it has always worked & about a month ago I started using Ferdi. I didn't transfer my account from Franz, but started with a new one in Ferdi and added all my services manually. Since then, Teams has never worked when I started Ferdi. I was able to log in, but then it stops working. But I did get it working this way:
1. log in to Teams (or just start up Ferdi if you had logged in during a previous session)
2. right click the Teams service & choose 'Disable service'.
3. right click the Teams service & choose 'Enable service'.
4. you should be good to go ;) Hopefully this can help some of you out!

**Comment by ggblbl** [comment]
I didn't to have this problem before, but with the latest update (5.5.0-gm) I now do too. I already removed the service and re-added it and the login screen worked fine, but the actual service itself just doesn't want to show..

**Comment by kytwb** [comment]
@ggblbl We are aware of the regression in 5.5.0-gm, this is being addressing in https://github.com/getferdi/ferdi/issues/536 for v5.5.0. 
Thanks for bearing with us! 🙏

**Comment by dpkonofa** [comment]
I’m using 5.4.3 and not the 5.5-GM release. How far back did the regression go?

**Comment by dpkonofa** [comment]
Just updated to 5.5.0 and the issue still persists. Hopefully this gets resolved soon. Still confused why I have 0 issues in Franz but can't get this to work at all, on multiple machines, through Ferdi.

**Comment by ckkoen** [comment]
I'm also running the 5.5.0 stable and for me it has been solved. I did do an uninstall + install of Ferdi instead of just update it. I then had to re-login to every service I had. I don't know if that makes any difference.

**Comment by dpkonofa** [comment]
I did too, unfortunately. I’m on a Mac so I used AppCleaner to make sure all the .plist files and Library folders were removed also. Still no luck. I also downloaded the latest Teams recipe from the recipes repo on here and swapped that out but it still just sits there loading. 😭😭

**Comment by dpkonofa** [comment]
Still relevant. Just tested yesterday and it's still not working.

**Comment by dpkonofa** [comment]
Not sure what changed but Microsoft Teams suddenly started loading this morning after Microsoft sent out a status update saying that the platform was down and the issue had been resolved. It now works without any issues and all the functions work. Fingers crossed that this is permanent... I wonder if the issue was on their end this whole time.  :-/

**Comment by 1Maxnet1** [comment]
This just happened to me today. I got three different teams accounts, and all three of them stopped working. What is the current status of this issue?

**Comment by NetPumi2** [comment]
I tried almost all the solutions above... none of them works. :(

**Comment by fuzzy76** [comment]
Three days ago, my Teams service suddenly started doing this. Clearing the data (as described above) and restarting Ferdi fixed it. On 5.5.0.

**Comment by ItsANoBrainer** [comment]
Every day I have a similar issue where I have to remove the service, re-add it, and relog in again because when I open Ferdi in the morning for work, it gives the mentioned error.

**Comment by fuzzy76** [comment]
Yeah, my fix yesterday only worked for an hour. :-/

**Comment by kid-three** [comment]
Same thing. This week it started acting up. I;ve had to remove and re-add it about 2-3x a day.

**Comment by ItsANoBrainer** [comment]
Console picture for reference:

![image](https://user-images.githubusercontent.com/6852526/109990351-4f966000-7cd7-11eb-9696-985be727bb0a.png)

**Comment by kaibrune** [comment]
Same for me :( My Teams service suddenly started doing this starting this week.

**Comment by kaibrune** [comment]
![image](https://user-images.githubusercontent.com/33369042/110252044-cd7e9380-7f83-11eb-94f7-92e65bb53c22.png)

I got another error message.

**Comment by fuzzy76** [comment]
Then it's another issue.

**Comment by Gaboxondo** [comment]
same error for me....

**Comment by FriendlyTroll** [comment]
I'm just writing to report that I don't have these issues on Linux. I'm using KDE Neon 5.21.4 which is based off of Ubuntu 20.04.

Ferdi version 5.5.0
Electron 8.2.3
Node.js v12.13.0
Platform: linux

I have 2 different Teams account, both working fine, including calls and screen share.

Ferdi was installed from deb package.

**Comment by mloskot** [comment]
Fresh installation
Ferdi 5.5.0
Platform: Windows 10 (20H2)

- Add Teams service
- Sign in to my work or school account
- Username, password, 2FA code, all done
- Close Ferdi
- Re-launch Ferdi
- Go to Teams service
- Observe either completely blank page or the try again as in https://github.com/getferdi/ferdi/issues/475#issuecomment-792337849

Here is the log generated during Ferdi startup and loading of the Teams: [ferdi.log](https://github.com/getferdi/ferdi/files/6548233/ferdi.log)

The workaroud in https://github.com/getferdi/ferdi/issues/475#issuecomment-611428250 does not solve the problem for me.
Removing the Teams completely and re-configuring it does not solve the problem for me either.

**Comment by vraravam** [comment]
@mloskot - we have finally released the latest nightlies - which bring in a lot of changes to the recipes as well. Could you please try with the [latest nightly](https://github.com/getferdi/ferdi/releases) - and report back if the issue is still present?

**Comment by mloskot** [comment]
@vraravam TL;TR: The 5.6.0-beta.5 works!

Here is what I've done:
1. Uninstall Ferdi 5.5.0
2. Wipe out `%USERPROFILE%\AppData\Roaming\Ferdi` completely
3. Install 5.6.0-beta.5 
4. Launch and sign in to the Ferdi account
5. Sign in to one Slack workspace and 
6. Sign in to Teams workspace and re-launch
7. Teams loaded fine
8. Sign in to another two Slack workspaces
9. Re-launch and the Teams loaded fine again.

No idea if the 1. and 2. is strictly necessary, but I prefer to start with clean slate when I test a software.

Thanks!

**Comment by vraravam** [comment]
@mloskot - thanks for trying it out and the detailed steps for others to follow as well. But, the beta itself is quite old. The nightly released within the past 24 hrs is quite stable - in case you want to try it out. We are getting ready to release the final 5.6.0 in a matter of days.

**Comment by mloskot** [comment]
@vraravam I simply followed to https://github.com/getferdi/ferdi/releases as you linked in the https://github.com/getferdi/ferdi/issues/475#issuecomment-848918466 and I guess you meant the link to https://github.com/getferdi/nightlies/releases

Do I just download e.g. 5.6.0-nightly.48 and run the installer **without** uninstalling the beta I'm currently using?

------

By the way, when Ferdi is released, I will install it via https://github.com/microsoft/winget-cli/ as I usually do:

```console
C:\>winget search ferdi
Name  Id                 Version
--------------------------------
Ferdi AmineMouafik.Ferdi 5.5.0

C:\>winget install --id AmineMouafik.Ferdi
```

**Comment by vraravam** [comment]
@mloskot - please uninstall the beta and install the nightly - the profile folder will get automatically updated on first-startup of the app.

Yes, there is some plan to support package managers - I will make sure that win-get is in the list (if not already present)

**Comment by fuzzy76** [comment]
I installed 5.6 nightly over 5.5. On first launch Teams was still blank. I deleted and re-added the service. It seems fine for now (tried restarting Ferdi and it still worked).

**Comment by vraravam** [comment]
Thanks for getting back @fuzzy76 - can we close this bug now?

**Comment by fuzzy76** [comment]
I wouldn't recommend it after such short time. This issue has numerous examples of people that "fixed" it, only to get the issue back after a day or two (including myself).

**Comment by fuzzy76** [comment]
It still works for me, so it seems fixed. :)

**Comment by vraravam** [comment]
Closing the ticket now.

**Comment by mll0** [comment]
The nightly seems to fix the bug for me too.

**Comment by fredfredfred** [comment]
Clear cache as described here: https://github.com/getferdi/ferdi/issues/475#issuecomment-790716019
And delete all cookies in the Service Developer Tools helped and did the trick for me.
