### ISSUE TITLE
Tray icon missing in XFCE Linux

### ISSUE THREAD

**Issue by deadmeu** [getferdi/ferdi#657]
**Describe the bug**

Tray icon missing with update to 5.5.0.

**To Reproduce**

1. Enable system tray icon for Ferdi in settings
2. You will see no tray icon for Ferdi

**Desktop:**

- Version: 5.5.0 (x64)
- Electron: 8.2.3
- Node.js: v12.13.0
- Platform: Linux (Manjaro)
- DE: XFCE 4.14
Running without an account.

**Additional context**

Installed from the AUR using the [`ferdi-bin` package](https://aur.archlinux.org/packages/ferdi-bin/).
Worked fine in the previous stable release. Updated, and it was gone.

**Comment by falsified** [comment]
Adding variance to reported issue:

Tray icon missing in AppImage 5.5.0

- Platform: Arch Linux
- Running local account

**Comment by obvionaoe** [comment]
It was also missing in Manjaro for me, but then I toggled on and off the "Show Ferdi in system tray" option and Ferdi crashed, but after I restarted it, the tray icon appeared!

**Comment by JCGoran** [comment]
Can confirm, with the following setup:
* Debian Sid
* Ferdi 5.5.0 from Flatpak
* no account
* XFCE4 panel 4.14.3

I tried toggling the "Show Ferdi in system tray" as per the comment above, as well as refreshing the panel itself, but unfortunately it did not work.
As a temporary workaround, I've set the Ferdi window to be "Always on Visible Workspace", so now it's at least more easily accessible when working with multiple workspaces.

**Comment by dialvarezs** [comment]
I can confirm this too:
-  Fedora 32
- Gnome 3.36.1 with KStatusNotifierItem/AppIndicator Support extension
- Ferdi 5.5.0 from Flathub

It was working ok before last update. I tried disabling and enabling again the option of the tray icon, but nothing happens. I don't see any errors either if I run it from the terminal.

**Comment by andrecavallari** [comment]
Also in linux MINT, clicking "X" logs out the user and closes the application

**Comment by kytwb** [comment]
This has been potentially fixed via https://github.com/getferdi/ferdi/pull/741 and made available via [5.5.1-nightly.14](https://github.com/getferdi/nightlies/releases/tag/v5.5.1-nightly.14).  
Feedback from Linux users on the nightly welcome to confirm if this fixes it 🙏 
Closing in favor of https://github.com/getferdi/ferdi/issues/484, let's continue the discussion there if needed.  
Thank you everyone for bringing this up to our attention!

**Comment by Vioner** [comment]
@kytwb @kris7t  I'm also on Manjaro 20.0.1 XFCE 4.14 and here the tray icon is still missing eventhough I tried the nightlies **(14 and 15) .** 
I've tried the nightly build and I don't get any errors relating it though. 

When I have the tray icon enabled in settings on nightly **14** and then click it to disable, I get:
```
TypeError: Cannot read property 'setContextMenu' of null
    at TrayIcon._updateTrayMenu (/tmp/ferdi-5.5.1-nightly.14/resources/app.asar/lib/Tray.js:1:1251)
    at IpcMainImpl.<anonymous> (/tmp/ferdi-5.5.1-nightly.14/resources/app.asar/lib/Tray.js:1:1683)
    at IpcMainImpl.emit (events.js:215:7)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3851:15)
    at WebContents.emit (events.js:210:5)
```

This doesn't happen on nightly 15 and I suppose that version also has the fix.

**Comment by kris7t** [comment]
@Vioner You can try the [xfce4-statusnotifier-plugin](https://docs.xfce.org/panel-plugins/xfce4-statusnotifier-plugin) to make XFCE display tray icons based on the StatusNotifier protocol. The Electron version that Ferdi 5.5.0 is built in has removed support for any tray icons except StatusNotifierItems, so your DE has to support them to be visible. Nightly 15, as you can see, fixes some bugs with StatusNotifier tray icon creation, but can't do anything if you DE does not handle them at all.

**Comment by k0d3r1s** [comment]
@kris7t thank you for your comment. I'm running Mate DE, installed https://packages.debian.org/sid/xfce/mate-sntray-plugin and icon now appears in panel :)
