### ISSUE TITLE
Tray icon missing on Linux in 5.5.0

### ISSUE THREAD

**Issue by don-andruha** [getferdi/ferdi#697]
**Describe the bug**

There's no tray icon in this version of Ferdi.
Before it I use version 5.4.4-beta1 and all works fine.

**To Reproduce**

1. Download version [5.5.0](https://github.com/getferdi/ferdi/releases/tag/v5.5.0)
2. Enable close to tray.

**Expected behavior**
It should show the application tray icon.

**Screenshots**
N/A

**Desktop:**
* OS: Linux Mint 19.1 Cinnamon x86_64
* Ferdi Version 5.5.0-2116 Stable
* Server Used: N/A

Debug information: https://debug.getferdi.com/e254d1af-496b-40e0-b4f5-a1e052bddc7c

**Comment by dieggywegz** [comment]
Can confirm this is happening to me too.
Pop OS 20.04

**Comment by dialvarezs** [comment]
Seems to same as #657

**Comment by xenithorb** [comment]
Same with 5.5.0 Flatpak from flathub on Fedora 31

**Comment by arnishow** [comment]
Same with Ubuntu 20.04. Was working fine before 5.5.0.

**Comment by dev-dd** [comment]
Happens randomly on Manjaro Gnome with Flatpak

**Comment by kytwb** [comment]
This has been potentially fixed via https://github.com/getferdi/ferdi/pull/741 in [5.5.1-nightly.14](https://github.com/getferdi/nightlies/releases/tag/v5.5.1-nightly.14).  
Feedback from Linux users on the nightly welcome to confirm if this fixes it 🙏

**Comment by kytwb** [comment]
Closing in favour of https://github.com/getferdi/ferdi/issues/484. Thank you everyone for bringing this up to our attention!

**Comment by don-andruha** [comment]
> This has been potentially fixed via #741 in [5.5.1-nightly.14](https://github.com/getferdi/nightlies/releases/tag/v5.5.1-nightly.14).
> Feedback from Linux users on the nightly welcome to confirm if this fixes it pray

I checked your nightly [build 5.5.1-nightly.14](https://github.com/getferdi/nightlies/releases/tag/v5.5.1-nightly.14), but did not see any changes. Tray icon still missing.

**Comment by pamela-p6** [comment]
same here, noticed:
TypeError: Cannot read property 'setContextMenu' of null
    at TrayIcon._updateTrayMenu (/opt/Ferdi/resources/app.asar/lib/Tray.js:1:1251)
    at IpcMainImpl.<anonymous> (/opt/Ferdi/resources/app.asar/lib/Tray.js:1:1683)
    at IpcMainImpl.emit (events.js:215:7)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3851:15)
    at WebContents.emit (events.js:210:5)
TypeError: Cannot read property 'setContextMenu' of null
    at TrayIcon._updateTrayMenu (/opt/Ferdi/resources/app.asar/lib/Tray.js:1:1251)
    at IpcMainImpl.<anonymous> (/opt/Ferdi/resources/app.asar/lib/Tray.js:1:1683)
    at IpcMainImpl.emit (events.js:215:7)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3851:15)
    at WebContents.emit (events.js:210:5)


@OL7(RHEL) + mate

**Comment by kris7t** [comment]
Interestingly, for me, after building the ea5a5932 from the `develop` branch with Electron 8.2.5, the tray icon appears on Waybar (I use sway as a Wayland compositor), if I run Ferdi in release mode (`ELECTRON_IS_DEV=0`). In dev mode, however, I do errors with calling `setContextMenu` on `null`. I also get similar errors when I toggle "Show Ferdi in system tray" to off.

When I restart Waybar (`org.kde.StatusNotifierWatcher` disappears from the session D-Bus, the reappears as the new Waybar instance is initialized), the tray icon disappears. However, it comes back when I toggle "Show Ferdi in system tray" to off and then back on. I guess we would have similar behavior in GNOME Shell whenever the screen is locked.

**Comment by andrecavallari** [comment]
Reopening this issue, now the tray icon is visible, but after a while it just disappear, then I have to enter config, disable and re-enable the option to make it appear again in tray

**Comment by dev-dd** [comment]
On Manjaro: the tray icon disappears after suspension. Gotta pkill the process to make it work again.

**Comment by kris7t** [comment]
@dev-dd That's with the latest nightly, right? In that case we might need to hook into session unlock / suspend resume somehow, to update the icon...

**Comment by dialvarezs** [comment]
It's working for me in the last nightly after lock/suspend (before that wasn't). I'm on Fedora 32 with gnome 3.36.

**Comment by tpapamichail** [comment]
Tray icon still missing.  The tray icon is visible, but after a while it just disappear.
Mint Cinnamon 20.04, 5.6.0-beta2

**Comment by tezvi** [comment]
The icon disappear after wake up on Ubuntu 20.4

**Comment by tezvi** [comment]
Not sure why is this closed. The tray icon is still missing on Ubuntu 20.04.2 LTS and Ferdi 5.5.0.
When started an icon is rendered but with no submenus. After system wakeup or some time of inactivity it just disappears.

**Comment by kris7t** [comment]
Closed because it's a duplicate of https://github.com/getferdi/ferdi/issues/437
