### ISSUE TITLE
Blank service icon when placing an image on a 'custom website' 

### ISSUE THREAD

**Issue by agichim** [getferdi/ferdi#780]
This happens on 5.5.1-nightly-15

**Comment by ragusa87** [comment]
I have the same issue on 5.5.0 by placing an image on a standard service.
The demo:
[ferdi-2020-05-29_10.19.55.mp4.zip](https://github.com/getferdi/ferdi/files/4700488/ferdi-2020-05-29_10.19.55.mp4.zip)

The custom icon:
![private-keep](https://user-images.githubusercontent.com/1695207/83238119-41d70b80-a196-11ea-9486-411a8e413d25.jpg)

**Comment by deimosfr** [comment]
Same for me and can't get the original back as well

**Comment by penCsharpener** [comment]
same here, tried png in different sizes but no luck

**Comment by yann1cks** [comment]
I am in 5.5.0 (Windows 10) and I have the same problem when placing an image to a custom website. I tried png (with transparency) and jpgs in different sizes.

**Comment by ragusa87** [comment]
Same for me:  All services where I to tried modify the icon have now no icon anymore after a restart.

**Comment by jbirnick** [comment]
Please tag this as a bug.

**Comment by janjurek** [comment]
I believe this is duplicate of this issue https://github.com/getferdi/ferdi/issues/595 no news there either though.

**Comment by agichim** [comment]
I've solved it like this. 

https://github.com/agichim/ferdi-recipe-custom-website

**Comment by DeFiDude** [comment]
Same issue here, on 5.5.0 for windows and I can't get a custom icon for any default services.

I've tried both PNG and JPG, changing the icon size, etc.

**Comment by jokester01au** [comment]
I dug into this a little and it appears to be caused by a mismatch between what the "Save Service" PUT call sends from the client and what the server expects. If I set a custom icon, then the body of the PUT call is the icon data and nothing else, which returns a 400 error (NB this error is not reported to the user, it is only visible in the network tab of the developer tools). If I edit any of the other fields, as well as changing the icon, the icon is never sent.

**Comment by stevengliebe** [comment]
Try 5.6.0-beta.2 per #595. That fixed the issue for me.

https://github.com/getferdi/ferdi/releases

**Comment by donagrejja** [comment]
This is still an issue afaik ? at least on 5.5.0

**Comment by mlostekk** [comment]
Yes, having the same issue on `Version 5.5.0 (5.5.0.2116)`

**Comment by donagrejja** [comment]
This is still an issue. No update to Ferdi since issue was discovered.

**Comment by cristianmenghi** [comment]
Same problem 5.5.0.2116 on MacOS.

**Comment by salsa2k** [comment]
Any info about this issue? Looks like is there have a long time :(

**Comment by juanluisbaptiste** [comment]
It works in 5.6 beta2

**Comment by mlostekk** [comment]
> It works in 5.6 beta5

any eta for that?

**Comment by mhatvan** [comment]
Cannot reproduce this, seems it was fixed by the PR linked above.

Custom .svg icon shows correctly on both macOS and Ubuntu, also after restarting Ferdi.

**Comment by indeed-a-genius** [comment]
The issue is still present in 5.6.3, on Windows 10.
From the other comments I suspect it's present on Windows only.
