### ISSUE TITLE
Slack - cannot authenticate / access 

### ISSUE THREAD

**Issue by wernerdiers** [getferdi/ferdi#825]
**Bug description:**
Slack in my organization is tied to Okta and Google authentication.
From a clean install, i add Slack service to my workspace.  I enter my credentials, then i get the Okta console and then it is stuck in the Sing in screen.

Other services that uses Okta or Google auth are working (e.g. Gmail, Trello, Evernote, etc)

**Steps to reproduce:**
1. Slack tied to Okta and Google authentication.
2. From a clean install, add Slack service to your workspace. 
3. Enter  credentials
4. Then it is stuck in the Sing in screen instead of login to the Slack group

**Expected behavior**
Be able to access Slack group and channels after authentication

**Screenshots**

**Environment:**

- Operating System: macOS Mojave
- Ferdi Version: 5.5.0.2116
- Server: Ferdi with account

- Debug information:
Attached

[devconsole.log](https://github.com/getferdi/ferdi/files/4789651/devconsole.log)

[debugingo.log](https://github.com/getferdi/ferdi/files/4789654/debugingo.log)

**Comment by raicerk** [comment]
Hi, I have the same problem, my slack use saml authentication, when I enter the data to login, the callback of slack return the login of slack and don't having access

**Comment by wernerdiers** [comment]
Hi team, just checking if there is an update.

**Comment by wernerdiers** [comment]
@raicerk were you able to workaround this issue?

**Comment by gleonet** [comment]
Same problem here. Slack + Google authentication doesn't work with Ferdi

Ferdi Version: 5.5.0.2116
OS : Ubuntu 20.04

**Comment by raicerk** [comment]
@wernerdiers no, I have not been able to solve it, so I analyzed, the problem is in the forwarding of the authentication keys that google has

**Comment by Malwurf** [comment]
Same issue on Ubuntu 20.04.1 LTS | Ferdi version 5.5.0 -> after logout from slack can't log in with 'Sign in with Google'

**Comment by YNedderhoff** [comment]
I have the same problem on MacOS 10.14.5

**Comment by wernerdiers** [comment]
This is still an issue

**Comment by wernerdiers** [comment]
This is still an issue

**Comment by noBotHereDude** [comment]
> Slack in my organization is tied to Okta and Google authentication.
> From a clean install, i add Slack service to my workspace. I enter my credentials, then i get the Okta console and then it is stuck in the Sing in screen.

Use Right Click in the bottom msg link (Open in browser) then select "Open link in Ferdi".

**Comment by Shadester** [comment]
I also have this problem, it will go back to the slack login screen after tapping on the user.

**Comment by vraravam** [comment]
This has been fixed in the latest versions of the recipe (and since I see that some of you are also on v5.5.0 of Ferdi - that also needs to be upgraded to the latest). Could I please request you to install the versions from [this google drive folder](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)? (This is because the CI process to build and publish the nightlies are currently broken and being worked on.
I have uploaded the versions only for macos, for others, please follow the [manual steps for troubleshooting recipes](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)

**Comment by Shadester** [comment]
Using the Arm build 2021-May-15-19-59 - 0e0416ff and seeing this issue.

**Comment by vraravam** [comment]
@Shadester - please see if this fixes the "corrupt file" issue: https://github.com/getferdi/ferdi/issues/875#issuecomment-841679581

**Comment by Shadester** [comment]
Yes, it does.

**Comment by Shadester** [comment]
I can still not login on slack. Might be the Okta login, but it will do the same as was decribed above, back to the login page again.

**Comment by vraravam** [comment]
Something weird is going on. I was able to use Slack with Okta Oauth without any issues.

**Comment by rblanca** [comment]
same here unable to connect using SAML

**Comment by vraravam** [comment]
I'm on the same nightly 66 - and am able to login into a Slack team that is managed by okta. Can you please ensure that you have not manually edited the slack recipe files? and that you have the default settings for user-agent, etc? Are you running via a proxy?

**Comment by rblanca** [comment]
Yeap confirmed...clean install, using SAML with my company google's hosted email....

**Comment by vraravam** [comment]
Is this still an issue? I'm unable to pinpoint what might be the issue - since I have the same setup (slack with okta SSO, etc) on a mac and I dont see any of the issues mentioned. At this point, I'm running v73 of the nightlies.

**Comment by Shadester** [comment]
I tried v73, but I can't add any services. When opening the "available services" screen, I get a "something went wrong" message and I can't add any. So I don't know if it works.

**Comment by vraravam** [comment]
@Shadester - pls try v74 which I just released. This should be fixed now and you should be able to add new services.

**Comment by Shadester** [comment]
I was able to see and add  the service, but still no luck in adding the Slack workspace.

**Comment by DarylGraves** [comment]
I am also having the same issue here. I enter my credentials, get redirected to authorise Google and then for a fraction of a second I see it prompt me for my MFA Code before it reverts back to the Slack login screen.

**Comment by esaporski** [comment]
I was having the same problem, being redirect to the login screen after putting my credentials, but I fixed it editing the service configuration and adding `Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0` to the **User Agent** setting:

![ferdi_slack](https://user-images.githubusercontent.com/22015815/126889718-d456a866-f965-4382-a391-288b6f088ec8.png)

**Comment by vraravam** [comment]
Thanks for confirming @esaporski - this is a validation that the user-agent override works and that the slack authentication setup is somehow different to some of the users which is causing this weird behavior.

**Comment by Shadester** [comment]
Awesome! It works for me now.

**Comment by DarylGraves** [comment]
It seems a bit strange to me that this issue has been closed when we've found a potential workaround but no fix has been implemented. Is the expectation that everyone who wants to use Slack in Ferdi should do a Google search until they stumble across this page?

**Comment by vraravam** [comment]
@DarylGraves - we can alway reopen the ticket. But, afaik, I too use Slack via Google/okta - and have not seen the issue that was reported. I had implemented the exposure of the user-agent with the intention of [this comment](https://github.com/getferdi/ferdi/issues/825#issuecomment-886153383). I feel that this is accomplished by this comment.

**Comment by DarylGraves** [comment]
Ok no worries, thanks Vijay, and thank you for making this project what it is today!

**Comment by Shadester** [comment]
I would add this to the FAQ or readme, so people would have an easier time to figure out the steps to fix it.

**Comment by vraravam** [comment]
Excellent suggestion @Shadester .
Tagging @kytwb since I dont know how to add this to the "Help Center" on the getferdi website

**Comment by rblanca** [comment]
Confirmed @esaporski works
