### ISSUE TITLE
External links are opening inside of Ferdi

### ISSUE THREAD

**Issue by webworker01** [getferdi/ferdi#941]
**Bug description:**
External links are opening inside of Ferdi

**Steps to reproduce:**

1. Get a message with an external link
2. Click on the link
3. Link opens up in a Ferdi electron window

**Expected behavior**

Links open in my default browser

**Comment by EpoxyD** [comment]
Having the same issue. Currently on a Wiki page inside of my Github service, from which I cannot get back into Github.

**Comment by LongJohn-Silver** [comment]
> Having the same issue. Currently on a Wiki page inside of my Github service, from which I cannot get back into Github.

If you would like to go back to GitHub you could open the navigation bar and click the home button, or write the URL.

**Comment by papergum** [comment]
This issue is still relevant. Please address.

**Comment by ccioanca** [comment]
Middle clicking links seems to work; opening them in your default browser, but left clicking opens inside a new ferdi window.

**Comment by Julian88Tex** [comment]
`CMD + Left Clik` is a workaround

**Comment by papergum** [comment]
does not work on windows.

--

Jakob Schmitt
Strehleranger 11
81735 München

phone: +49 176 21 53 64 10
mail: mail@jakobschmitt.com


Am Mo., 1. März 2021 um 07:22 Uhr schrieb Julian Joseph <
notifications@github.com>:

**Comment by Julian88Tex** [comment]
@papergum good point. Just added that clarification to my comment. Thanks.

**Comment by Julian88Tex** [comment]
One more note, I noticed even `CMD + Left Click` doesn't work with every link in Ferdi on a mac. For example, the "Join Google Meet Meeting"/"Join Zoom Meeting" link on Slack's Google Calendar app still opens a new Ferdi window. The only workaround is to right-click method.

<img width="223" alt="Screen Shot 2021-03-01 at 10 08 14 AM" src="https://user-images.githubusercontent.com/459099/109539335-0b585500-7a76-11eb-8663-bf1aed5a4a02.png">
<img width="162" alt="Screen Shot 2021-03-01 at 10 08 23 AM" src="https://user-images.githubusercontent.com/459099/109539353-0f847280-7a76-11eb-8233-2886aa838d6f.png">

**Comment by derjohn** [comment]
Shift + Left Click in Linux. (Ferdi 5.6.0 nightly 48)

**Comment by vraravam** [comment]
Your normal shortcut key combo in the browser of your OS - that same keyboard shortcut should work now. Please check with the latest beta released approx 24 hrs ago.

**Comment by EpoxyD** [comment]
These workarounds for opening links outside of Ferdi are ignoring the issue: external links should not be opened within the Ferdi application. Some of these windows have no ability to return to the previous window, so you are forced to reload the entire application.

**Comment by jnvillar** [comment]
Still happening on latest nightly (5.6.0-nightly.71).

This is especially annoying when starting zoom call in slack. The call opens a web page on ferdi which starts the zoom app, the problem is that I can't go back in ferdi from that zoom page, the only thing I can do is kill ferdi and open it again

**Comment by vraravam** [comment]
@jnvillar - did the right-click context menu not work for you to navigate back? There's also a keyboard shortcut for the same.

**Comment by jnvillar** [comment]
No, that shortcut does nothing for me. I also tried view -> go back. 

The strange thing is that when I start a zoom meeting another window is open with the zoom page, and the original window where ferdi was is black. 

I tried right click -> back and view -> go back on the zoom page and nothing happens, same in the black screen

**Comment by vraravam** [comment]
@jnvillar : Can you please specify more details? What OS? What service? is this from a custom service or one of the packaged ones? What's the recipe version (found in the bottom of the preferences page for that service)?

**Comment by jnvillar** [comment]
os: macOs Catalina
service: slack
recipe: 1.0.16

opened window
![Screen Shot 2021-06-30 at 10 57 34](https://user-images.githubusercontent.com/7551569/123973238-fb07a680-d991-11eb-9426-65a61f53d554.png)

ferdi
![Screen Shot 2021-06-30 at 10 57 44](https://user-images.githubusercontent.com/7551569/123973274-022eb480-d992-11eb-9ba6-03bd9dc9b0a7.png)

desktops
![Screen Shot 2021-06-30 at 10 57 51](https://user-images.githubusercontent.com/7551569/123976270-65214b00-d994-11eb-877a-93da2290ae43.png)

(zoom app is open in another monitor)

This happens when I click on new call in slack (the icon with a phone)

**Comment by vraravam** [comment]
Thanks for the quick turnaround @jnvillar .

Unfortunately, I don't have a slack account that's integrated with zoom for me to test and provide a solution. The only thing that comes to mind is for you to right-click on the phone icon - and explicitly say "open in ferdi" or "open in default browser". Not sure which one works for you - or if neither of the solutions work.
Please try and get back.

**Comment by jnvillar** [comment]
I get this option

![Screen Shot 2021-06-30 at 12 10 22](https://user-images.githubusercontent.com/7551569/123985809-268f8e80-d99c-11eb-98a2-29bfb633f20d.png)

When clicked, it opens slack in chrome but it does not makes the call. I could use this to start the call from chrome though. Is not ideal but at least I don't have to kill ferdi every time I want to make a call.

**Comment by vraravam** [comment]
thanks - I agree this is not ideal, but without being able to replicate what you see, its quite tough to find a proper solution. 

We are also debating whether its useful to allow the ability to open links in the default browser vs in Ferdi in an overlay or in the main webview of Ferdi itself - this is a topic that was discussed internally by a couple of us. Such an ability will allow the user (you) to choose the required behavior at a global level and at each service-level as well. But - again, these are just initial discussions. If you feel this can be useful - plesae create a card and detail it out so that it can be put to vote and implemented.

**Comment by jnvillar** [comment]
sure, I can create it. Can you point me where?

**Comment by aruiz14** [comment]
I find this bug very annoying, especially because it forces you to completely quit Ferdi and open it again (unlike accidentally closing the window with `Cmd + W`, which can be solved by clicking on the Ferdi tray icon).
The experience is even worse if you are the one receiving the call, not starting it. You can always start the call from the Zoom app (not ideal) to bypass this problem, but can't decide how others call you, so in practice, I have to restart Ferdi entirely every time I receive a call.

I believe this behavior was not always present, at least on some of the betas. Sadly, I cannot remember which specific one was working well. Maybe the links handling changed in some of them?

It would be great if this could be solved.
